"""NuRoute Python SDK — provider-agnostic LLM inference control plane."""

from .client import NuRouteClient, ProjectClient
from .client import AICPClient  # deprecated alias, see client.py
from .async_client import AsyncNuRouteClient, AsyncProjectClient
from .async_client import AsyncAICPClient  # deprecated alias, see async_client.py
from .errors import NuRouteError
from .errors import AICPError  # deprecated alias, see errors.py
from .types import (
    ApiKey,
    AuthResponse,
    Candidate,
    ChatCompletionResponse,
    ChatMessage,
    CreateKeyResponse,
    ExcludedProvider,
    InviteInfo,
    InviteResponse,
    Invitation,
    ModelInfo,
    Org,
    Period,
    Project,
    ProviderBreakdown,
    ProviderConfig,
    ProviderTestResult,
    ReplayData,
    Recommendation,
    RequestDetail,
    RequestSummary,
    RoutingAlias,
    RoutingConfig,
    RoutingDecision,
    RoutingDecisionSummary,
    RoutingPolicy,
    RoutingStrategy,
    StrategyBreakdown,
    TimelineEvent,
    UsageBreakdown,
    UsageOverview,
    UsageRecommendations,
    UsageSeriesPoint,
    User,
    UserRole,
)

__all__ = [
    "NuRouteClient",
    "AsyncNuRouteClient",
    "AsyncProjectClient",
    "ProjectClient",
    "NuRouteError",
    # deprecated aliases — kept for backward compatibility, see client.py / async_client.py / errors.py
    "AICPClient",
    "AsyncAICPClient",
    "AICPError",
    # types
    "ApiKey",
    "AuthResponse",
    "Candidate",
    "ChatCompletionResponse",
    "ChatMessage",
    "CreateKeyResponse",
    "ExcludedProvider",
    "InviteInfo",
    "InviteResponse",
    "Invitation",
    "ModelInfo",
    "Org",
    "Period",
    "Project",
    "ProviderBreakdown",
    "ProviderConfig",
    "ProviderTestResult",
    "ReplayData",
    "Recommendation",
    "RequestDetail",
    "RequestSummary",
    "RoutingAlias",
    "RoutingConfig",
    "RoutingDecision",
    "RoutingDecisionSummary",
    "RoutingPolicy",
    "RoutingStrategy",
    "StrategyBreakdown",
    "TimelineEvent",
    "UsageBreakdown",
    "UsageOverview",
    "UsageRecommendations",
    "UsageSeriesPoint",
    "User",
    "UserRole",
]
